### ISSUE TITLE
session expired after 5 minutes on OIDC deployment with 3 nodes 

### ISSUE THREAD

**Issue by nnachefski** [guimou/nifi-on-openshift#9]
I used the oidc overlay w/ 3 nodes and users are able to login.  But, users are getting logged out after 5 minutes.  I've tried adjusting this with various nifi configs as well as tuning the OIDC client in keycloak but to no avail.  

What could be the tunable to fix this issue?

**Comment by nnachefski** [comment]
Any idea on what this could be?  It's definitely not a keycloak setting.  How do i get NiFi to keep from logging me out every 5 mins?

**Comment by nnachefski** [comment]
OIDC integration w/ NiFi seems like an after-thought.  I removed this and used direct LDAPS integration instead (with FreeIPA) and this works much better.  Closing...

**Comment by guimou** [comment]
Hi @nnachefski ! I'm really sorry taking this much time to answer. The issue is with NiFi itself, not really taken care of so far. The only solution for now is to increase the lifespan of the token, to go from 5mn (default for Keycloak for example) to something more suitable (with decreased security of course). Ref: https://issues.apache.org/jira/browse/NIFI-4890
I will leave this issue closed for the moment, I'm following the main one on NiFi.
